### ISSUE TITLE
增加支持alist离线下载作为下载器

### ISSUE THREAD

**Issue by karma-sun** [simon-ding/polaris#4]
未来版本，下载器能否支持采用alist的离线下载功能？现在网盘如此发达，想使用网盘做下载器

**Comment by simon-ding** [comment]
据我了解，alist的离线下载也是使用的第三方客户端，不可能是直接下载到网盘里的。我想问一下，支持alist的离线下载功能意义在哪？

**Comment by simon-ding** [comment]
> > 据我了解，alist的离线下载也是使用的第三方客户端，不可能是直接下载到网盘里的。我想问一下，支持alist的离线下载功能意义在哪？
> 
> alist新版本已经可以使用pikpak的离线功能直接下载文件到网盘，相信其它网盘的支持也在路上

那也就只有特定网盘才支持了。此程序暂时不会为了特定网盘而定制
