### ISSUE TITLE
设置登录用户密码后一直卡在登录界面

### ISSUE THREAD

**Issue by dnsdk** [simon-ding/polaris#5]
输入正确的用户名密码仍然会不断调到登陆界面，进不去主界面

**Comment by simon-ding** [comment]
1. 尝试使用浏览器无痕模式或者清理一下浏览器缓存，看问题是否还会出现
2. 如果不能解决，加入telegram群组，群里面交流

**Comment by simon-ding** [comment]
> 输入正确的用户名密码仍然会不断调到登陆界面，进不去主界面

http模式的bug，[最新版本](https://github.com/simon-ding/polaris/releases/tag/v0.11.1)已经解决

**Comment by simon-ding** [comment]
close
