### ISSUE TITLE
出错：拉不到相关视频的信息

### ISSUE THREAD

**Issue by midpoint** [simon-ding/polaris#6]
docker拉取要开代理，不然拉不动，使用的时候拉不到相关视频的信息，如图：
直接访问出错的链接是可以获取信息的
![1](https://github.com/user-attachments/assets/63f111e1-d934-41ae-b109-8530daf99a94)
![2](https://github.com/user-attachments/assets/ddc15df0-0526-4193-b8c8-283b118f5a18)

**Comment by simon-ding** [comment]
tmdb需要翻墙才能连接，要么在路由器上设置全局代理，要么可以在程序 常规-> 代理地址 填上局域网内的翻墙代理地址

**Comment by simon-ding** [comment]
我加了个文档说明这个问题：
https://simonding.gitbook.io/polaris/tmdb-fang-wen-wen-ti

**Comment by simon-ding** [comment]
close
